### ISSUE TITLE
Cannot build "Demo" project due to input files cannot be found

### ISSUE THREAD

**Issue by struuuuggle** [mmng-a/Neumorphismic#1]
Good work!
This is what I've been waiting for!

I tried to build the Demo project but failed to build it.
It seems the error is caused due to some missing files in `Demo/Views/`.
Are you sure you've already uploaded swift files in `Demo/Views`?

```
error: Build input files cannot be found: 
'<PATH_TO>/Neumorphismic/Demo/Views/DemosView.swift', 
'<PATH_TO>/Neumorphismic/Demo/Views/SettingsView.swift',
'<PATH_TO>/Neumorphismic/Demo/Views/ContentView.swift' 
(in target 'Demo' from project 'Neumorphismic')
```

**Comment by mmng-a** [comment]
Thank you, Mikiya!
I’m restructuring Neumorphismic, so I’ll tell you when finished. (I want finish by today)
I’m sorry.

**Comment by mmng-a** [comment]
I made it. Thank you!
